package com.sawal.ai;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class SpringAIProcessor {

    @Autowired
    private GeminiAPIClient geminiAPIClient;
    
    /**
     * Processes a natural language query by sending it to the Gemini API
     * and converting the response into an SQL query.
     *
     * @param naturalLanguageQuery the query in plain language
     * @return the SQL query (or response) generated by Gemini
     */
    public String processQuery(String naturalLanguageQuery) {
        // Send the query to Gemini and receive the raw response
        String response = geminiAPIClient.sendQuery(naturalLanguageQuery);
        // Parse the response to extract or convert it to SQL (adjust as needed)
        return geminiAPIClient.parseResponse(response);
    }
}
